plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/ClassMethodsDefinitions:
  Enabled: true
  EnforcedStyle: self_class
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInChaining: true
FactoryBot/ConsistentParenthesesStyle:
  Enabled: false
  # Use the same style as in other sources
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces
Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*'
Style/SymbolProc:
  Exclude:
    - 'db/migrate/*'
Layout/LineLength:
  Max: 125
Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
RSpec/NotToNot:
  EnforcedStyle: to_not
Rails/SkipsModelValidations:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
Rails/BulkChangeTable:
  Exclude:
    - db/migrate/2022*
RSpec/ImplicitExpect:
  EnforcedStyle: should
Naming/PredicateMethod:
  AllowedMethods:
    - acquire
    - release
AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
